export const AUX_THRESHOLD_TOKEN = Symbol('AUX_THRESHOLD');
export const REP_REGION_THRESHOLD_TOKEN = Symbol('REP_REGION_THRESHOLD_TOKEN');
export const REP_THRESHOLD_TOKEN = Symbol('REP_THRESHOLD');
