export enum OrderOperateTemplateEnum {
  CREATE_ORDER = 'CREATE_ORDER',
  UPDATE_ORDER = 'UPDATE_ORDER',
  CANCEL_ORDER = 'CANCEL_ORDER',
  REJECT_ORDER = 'CANCEL_ORDER',
  CONFIRM_ORDER_PAYMENT = 'CONFIRM_ORDER_PAYMENT',
  PUSH_ORDER_PAYMENT = 'PUSH_ORDER_PAYMENT',
  REGION_APPROVAL_ORDER = 'REGION_APPROVAL_ORDER',
  PROVINCE_APPROVAL_ORDER = 'PROVINCE_APPROVAL_ORDER',
  DIRECTOR_APPROVAL_ORDER = 'DIRECTOR_APPROVAL_ORDER',
}
